-- 🔒 SECURITY MIGRATION: RLS POLICIES
-- Generated by Atlas

-- 1. ALARMS (Private)
ALTER TABLE IF EXISTS alarms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own alarms" ON alarms;

CREATE POLICY "Users can manage their own alarms"
ON alarms
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 2. VITAL SIGNS (Private)
ALTER TABLE IF EXISTS vital_signs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own vital signs" ON vital_signs;

CREATE POLICY "Users can manage their own vital signs"
ON vital_signs
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 3. USER MEDICATIONS (Private Inventory)
ALTER TABLE IF EXISTS user_medications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own medication inventory" ON user_medications;

CREATE POLICY "Users can manage their own medication inventory"
ON user_medications
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 4. MEDICATIONS (Global Reference - Public Read)
ALTER TABLE IF EXISTS medications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read medications" ON medications;

CREATE POLICY "Authenticated users can read medications"
ON medications
FOR SELECT
TO authenticated
USING (true);

-- Note: Writes to 'medications' are restricted to service_role (admin) by default 
-- as no policy allows INSERT/UPDATE/DELETE for 'authenticated' role.